repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.931'
  hooks:
  - id: mypy
    files: pybm/

- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
    - id: black
      language_version: python3