repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.284
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.0
  hooks:
  - id: mypy
    files: pybm/
    exclude: pybm/third_party/
    args: ["--config=pyproject.toml"]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      types_or: [cython, pyi, python]
      args: ["--filter-files"]